name: firebas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^2.27.0
  provider: ^6.1.1
  get_it: ^7.6.7
  go_router: ^13.1.0
  dartz: ^0.10.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  path_provider: ^2.1.2
  uuid: ^4.3.3
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
