// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmvNGYWFHFClC9bjUB416MRJluwyJUJR0',
    appId: '1:274683707203:web:4bb5aabb1018c824f439f6',
    messagingSenderId: '274683707203',
    projectId: 'firebas-a395b',
    authDomain: 'firebas-a395b.firebaseapp.com',
    storageBucket: 'firebas-a395b.appspot.com',
    measurementId: 'G-GJR5MSRVQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8_W40Adh_5jddSnHln7U0kaNgBrVcHPk',
    appId: '1:274683707203:android:f68729823db6d520f439f6',
    messagingSenderId: '274683707203',
    projectId: 'firebas-a395b',
    storageBucket: 'firebas-a395b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKYJV_20j120MP5YcA5O5QokFEg-zsX10',
    appId: '1:274683707203:ios:c14814bf571fa597f439f6',
    messagingSenderId: '274683707203',
    projectId: 'firebas-a395b',
    storageBucket: 'firebas-a395b.appspot.com',
    iosBundleId: 'com.example.firebas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKYJV_20j120MP5YcA5O5QokFEg-zsX10',
    appId: '1:274683707203:ios:c182744b1b8e8b06f439f6',
    messagingSenderId: '274683707203',
    projectId: 'firebas-a395b',
    storageBucket: 'firebas-a395b.appspot.com',
    iosBundleId: 'com.example.firebas.RunnerTests',
  );
}
